[workspace]
members = [
  "iroh",
  "iroh-blobs",
  "iroh-base",
  "iroh-dns-server",
  "iroh-gossip",
  "iroh-metrics",
  "iroh-net",
  "iroh-docs",
  "iroh-test",
  "iroh-net/bench",
  "iroh-cli",
]
resolver = "2"

[profile.release]
debug = true

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false


[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
unused-async = "warn"

[patch.crates-io]
tokio-rustls-acme = { git = "https://github.com/n0-computer/tokio-rustls-acme", branch = "rustls-23" }
iroh-quinn = { git = "https://github.com/n0-computer/quinn", branch = "matheus23/diagnose-windows" }
iroh-quinn-udp = { git = "https://github.com/n0-computer/quinn", branch = "matheus23/diagnose-windows" }
iroh-quinn-proto = { git = "https://github.com/n0-computer/quinn", branch = "matheus23/diagnose-windows" }
quic-rpc = { git = "https://github.com/n0-computer/quic-rpc", branch = "flub/quinn11-rustls23" }
