[workspace]
members = [
  "iroh",
  "iroh-bytes",
  "iroh-base",
  "iroh-dns-server",
  "iroh-gossip",
  "iroh-metrics",
  "iroh-net",
  "iroh-sync",
  "iroh-test",
  "iroh-net/bench",
  "iroh-cli"
]
resolver = "2"

[profile.release]
debug = true

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false


[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
unused-async = "warn"

[patch.crates-io]
s2n-quic = { path = "../s2n-quic/quic/s2n-quic" }
s2n-quic-platform = { path = "../s2n-quic/quic/s2n-quic-platform" }
s2n-quic-rustls = { path = "../s2n-quic/quic/s2n-quic-rustls" }
s2n-quic-core = { path = "../s2n-quic/quic/s2n-quic-core" }
