---
- name: Update derper node
  hosts: derper
  become: yes

  tasks:
  - name: Make sure derper is stopped
    ansible.builtin.systemd:
      state: stopped
      enabled: yes
      name: derper
  - name: Fetch derper binary
    get_url:
      url: https://vorc.s3.us-east-2.amazonaws.com/derper-linux-amd64-latest
      mode: '0755'
      force: yes
      dest: /usr/local/bin/derper
  - name: Allow ports
    shell:
      cmd: sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/derper
  - name: Make sure derper is started
    ansible.builtin.systemd:
      state: restarted
      enabled: yes
      name: derper