# Run tests using the beta Rust compiler

name: Beta Rust

on:
  schedule:
    # 06:50 UTC every Monday
    - cron: '50 6 * * 1'
  workflow_dispatch:

concurrency:
  group: beta-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IROH_FORCE_STAGING_RELAYS: "1"

jobs:
  beta:
    uses: 'n0-computer/workflows/.github/workflows/beta.yaml@main'
    with:
      tests: 'n0-computer/iroh/.github.workflows/tests.yaml'

